"""SQLAlchemy database models.

This module re-exports all models from orderbot.db.models for backward
compatibility. New code should import directly from orderbot.db.models.
"""

# Re-export everything from the new package location
from .db.models import (
    Base,
    Category,
    ChatSession,
    Company,
    GlobalAttribute,
    GlobalAttributeAlias,
    GlobalAttributeOption,
    GlobalAttributeOptionAlias,
    Ingredient,
    IngredientAlias,
    IngredientCategory,
    IngredientMustMatch,
    IngredientStoreAvailability,
    IngredientUnit,
    ItemType,
    ItemTypeAlias,
    ItemTypeGlobalAttribute,
    ItemTypeIngredient,
    MenuItem,
    MenuItemAlias,
    MenuItemCategory,
    MenuItemIngredient,
    MenuItemSize,
    MenuItemSizeCategory,
    MenuItemSizePrice,
    MenuItemStoreAvailability,
    ModifierCategory,
    ModifierCategoryAlias,
    ModifierQualifier,
    NeighborhoodZipCode,
    Order,
    OrderItem,
    OverallCategory,
    ResponsePattern,
    SessionAnalytics,
    Store,
    UnrecognizedItemLog,
    UnrecognizedItemSuggestion,
)

__all__ = [
    "Base",
    "Category",
    "ChatSession",
    "Company",
    "GlobalAttribute",
    "GlobalAttributeAlias",
    "GlobalAttributeOption",
    "GlobalAttributeOptionAlias",
    "Ingredient",
    "IngredientAlias",
    "IngredientCategory",
    "IngredientMustMatch",
    "IngredientStoreAvailability",
    "IngredientUnit",
    "ItemType",
    "ItemTypeAlias",
    "ItemTypeGlobalAttribute",
    "ItemTypeIngredient",
    "MenuItem",
    "MenuItemAlias",
    "MenuItemCategory",
    "MenuItemIngredient",
    "MenuItemSize",
    "MenuItemSizeCategory",
    "MenuItemSizePrice",
    "MenuItemStoreAvailability",
    "ModifierCategory",
    "ModifierCategoryAlias",
    "ModifierQualifier",
    "NeighborhoodZipCode",
    "Order",
    "OrderItem",
    "OverallCategory",
    "ResponsePattern",
    "SessionAnalytics",
    "Store",
    "UnrecognizedItemLog",
    "UnrecognizedItemSuggestion",
]
