"""add_session_analytics_table

Revision ID: 07e15eb0609b
Revises: 90cdf9dc35e1
Create Date: 2025-12-13 20:24:17.730585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e15eb0609b'
down_revision: Union[str, Sequence[str], None] = '90cdf9dc35e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('had_items_in_cart', sa.Boolean(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('cart_total', sa.Float(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.Column('last_bot_message', sa.Text(), nullable=True),
    sa.Column('last_user_message', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('session_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_analytics_ended_at'), 'session_analytics', ['ended_at'], unique=False)
    op.create_index(op.f('ix_session_analytics_id'), 'session_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_session_analytics_session_id'), 'session_analytics', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_analytics_status'), 'session_analytics', ['status'], unique=False)
    op.drop_index(op.f('ix_abandoned_sessions_abandoned_at'), table_name='abandoned_sessions')
    op.drop_index(op.f('ix_abandoned_sessions_id'), table_name='abandoned_sessions')
    op.drop_index(op.f('ix_abandoned_sessions_session_id'), table_name='abandoned_sessions')
    op.drop_table('abandoned_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abandoned_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('message_count', sa.INTEGER(), nullable=False),
    sa.Column('had_items_in_cart', sa.BOOLEAN(), nullable=False),
    sa.Column('item_count', sa.INTEGER(), nullable=False),
    sa.Column('cart_total', sa.FLOAT(), nullable=False),
    sa.Column('order_status', sa.VARCHAR(), nullable=False),
    sa.Column('last_bot_message', sa.TEXT(), nullable=True),
    sa.Column('last_user_message', sa.TEXT(), nullable=True),
    sa.Column('reason', sa.VARCHAR(), nullable=False),
    sa.Column('session_duration_seconds', sa.INTEGER(), nullable=True),
    sa.Column('abandoned_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abandoned_sessions_session_id'), 'abandoned_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_abandoned_sessions_id'), 'abandoned_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_abandoned_sessions_abandoned_at'), 'abandoned_sessions', ['abandoned_at'], unique=False)
    op.drop_index(op.f('ix_session_analytics_status'), table_name='session_analytics')
    op.drop_index(op.f('ix_session_analytics_session_id'), table_name='session_analytics')
    op.drop_index(op.f('ix_session_analytics_id'), table_name='session_analytics')
    op.drop_index(op.f('ix_session_analytics_ended_at'), table_name='session_analytics')
    op.drop_table('session_analytics')
    # ### end Alembic commands ###
