"""Add ingredient_id to global_attribute_options

Revision ID: 20f3ceba966c
Revises: x4y5z6a7b8c9
Create Date: 2026-01-10 18:19:46.832298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f3ceba966c'
down_revision: Union[str, Sequence[str], None] = 'x4y5z6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_attribute_options', sa.Column('ingredient_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_global_attribute_options_ingredient_id'), 'global_attribute_options', ['ingredient_id'], unique=False)
    op.create_foreign_key(None, 'global_attribute_options', 'ingredients', ['ingredient_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('uq_ingredients_slug'), 'ingredients', type_='unique')
    op.drop_index(op.f('ix_ingredients_slug'), table_name='ingredients')
    op.create_index(op.f('ix_ingredients_slug'), 'ingredients', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredients_slug'), table_name='ingredients')
    op.create_index(op.f('ix_ingredients_slug'), 'ingredients', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_ingredients_slug'), 'ingredients', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'global_attribute_options', type_='foreignkey')
    op.drop_index(op.f('ix_global_attribute_options_ingredient_id'), table_name='global_attribute_options')
    op.drop_column('global_attribute_options', 'ingredient_id')
    # ### end Alembic commands ###
