"""Add global attribute normalization tables

Revision ID: 57a09fe179d1
Revises: mss_rename_001
Create Date: 2026-01-09 14:07:21.724225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a09fe179d1'
down_revision: Union[str, Sequence[str], None] = 'mss_rename_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_attributes_id'), 'global_attributes', ['id'], unique=False)
    op.create_index(op.f('ix_global_attributes_slug'), 'global_attributes', ['slug'], unique=True)
    op.create_table('global_attribute_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_attribute_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('price_modifier', sa.Float(), nullable=False),
    sa.Column('iced_price_modifier', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['global_attribute_id'], ['global_attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_attribute_id', 'slug', name='uq_global_attr_option_slug')
    )
    op.create_index(op.f('ix_global_attribute_options_global_attribute_id'), 'global_attribute_options', ['global_attribute_id'], unique=False)
    op.create_index(op.f('ix_global_attribute_options_id'), 'global_attribute_options', ['id'], unique=False)
    op.create_table('item_type_global_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('global_attribute_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('allow_none', sa.Boolean(), nullable=False),
    sa.Column('ask_in_conversation', sa.Boolean(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('min_selections', sa.Integer(), nullable=True),
    sa.Column('max_selections', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['global_attribute_id'], ['global_attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_type_id', 'global_attribute_id', name='uq_item_type_global_attr')
    )
    op.create_index('idx_item_type_global_attr_global_attr', 'item_type_global_attributes', ['global_attribute_id'], unique=False)
    op.create_index('idx_item_type_global_attr_item_type', 'item_type_global_attributes', ['item_type_id'], unique=False)
    op.create_index(op.f('ix_item_type_global_attributes_global_attribute_id'), 'item_type_global_attributes', ['global_attribute_id'], unique=False)
    op.create_index(op.f('ix_item_type_global_attributes_id'), 'item_type_global_attributes', ['id'], unique=False)
    op.create_index(op.f('ix_item_type_global_attributes_item_type_id'), 'item_type_global_attributes', ['item_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_type_global_attributes_item_type_id'), table_name='item_type_global_attributes')
    op.drop_index(op.f('ix_item_type_global_attributes_id'), table_name='item_type_global_attributes')
    op.drop_index(op.f('ix_item_type_global_attributes_global_attribute_id'), table_name='item_type_global_attributes')
    op.drop_index('idx_item_type_global_attr_item_type', table_name='item_type_global_attributes')
    op.drop_index('idx_item_type_global_attr_global_attr', table_name='item_type_global_attributes')
    op.drop_table('item_type_global_attributes')
    op.drop_index(op.f('ix_global_attribute_options_id'), table_name='global_attribute_options')
    op.drop_index(op.f('ix_global_attribute_options_global_attribute_id'), table_name='global_attribute_options')
    op.drop_table('global_attribute_options')
    op.drop_index(op.f('ix_global_attributes_slug'), table_name='global_attributes')
    op.drop_index(op.f('ix_global_attributes_id'), table_name='global_attributes')
    op.drop_table('global_attributes')
    # ### end Alembic commands ###
