"""add_abandoned_sessions_table

Revision ID: 90cdf9dc35e1
Revises: a1b2c3d4e5f6
Create Date: 2025-12-13 19:57:39.954461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90cdf9dc35e1'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abandoned_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('had_items_in_cart', sa.Boolean(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('cart_total', sa.Float(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.Column('last_bot_message', sa.Text(), nullable=True),
    sa.Column('last_user_message', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('session_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('abandoned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abandoned_sessions_abandoned_at'), 'abandoned_sessions', ['abandoned_at'], unique=False)
    op.create_index(op.f('ix_abandoned_sessions_id'), 'abandoned_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_abandoned_sessions_session_id'), 'abandoned_sessions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abandoned_sessions_session_id'), table_name='abandoned_sessions')
    op.drop_index(op.f('ix_abandoned_sessions_id'), table_name='abandoned_sessions')
    op.drop_index(op.f('ix_abandoned_sessions_abandoned_at'), table_name='abandoned_sessions')
    op.drop_table('abandoned_sessions')
    # ### end Alembic commands ###
