"""Add ingredient_id to attribute_options

Revision ID: 96e172af6a59
Revises: g1h2i3j4k5l6
Create Date: 2026-01-08 12:26:16.848898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e172af6a59'
down_revision: Union[str, Sequence[str], None] = 'g1h2i3j4k5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_by_pound_categories_slug'), table_name='by_pound_categories')
    op.drop_table('by_pound_categories')
    op.drop_index(op.f('idx_item_type_attributes_type'), table_name='item_type_attributes')
    op.create_index(op.f('ix_item_type_attributes_id'), 'item_type_attributes', ['id'], unique=False)
    op.create_index(op.f('ix_item_type_attributes_item_type_id'), 'item_type_attributes', ['item_type_id'], unique=False)
    op.drop_index(op.f('idx_menu_item_attr_sel_item'), table_name='menu_item_attribute_selections')
    op.create_index(op.f('ix_menu_item_attribute_selections_id'), 'menu_item_attribute_selections', ['id'], unique=False)
    op.create_index(op.f('ix_menu_item_attribute_selections_menu_item_id'), 'menu_item_attribute_selections', ['menu_item_id'], unique=False)
    op.drop_index(op.f('idx_menu_item_attr_values_attr'), table_name='menu_item_attribute_values')
    op.drop_index(op.f('idx_menu_item_attr_values_item'), table_name='menu_item_attribute_values')
    op.create_index(op.f('ix_menu_item_attribute_values_attribute_id'), 'menu_item_attribute_values', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_menu_item_attribute_values_id'), 'menu_item_attribute_values', ['id'], unique=False)
    op.create_index(op.f('ix_menu_item_attribute_values_menu_item_id'), 'menu_item_attribute_values', ['menu_item_id'], unique=False)
    op.drop_constraint(op.f('uq_neighborhood_zip_codes_neighborhood'), 'neighborhood_zip_codes', type_='unique')
    op.drop_index(op.f('ix_neighborhood_zip_codes_neighborhood'), table_name='neighborhood_zip_codes')
    op.create_index(op.f('ix_neighborhood_zip_codes_neighborhood'), 'neighborhood_zip_codes', ['neighborhood'], unique=True)
    op.create_index(op.f('ix_neighborhood_zip_codes_id'), 'neighborhood_zip_codes', ['id'], unique=False)
    op.create_index(op.f('ix_response_pattern_id'), 'response_pattern', ['id'], unique=False)
    op.create_index(op.f('ix_response_pattern_pattern_type'), 'response_pattern', ['pattern_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_pattern_pattern_type'), table_name='response_pattern')
    op.drop_index(op.f('ix_response_pattern_id'), table_name='response_pattern')
    op.drop_index(op.f('ix_neighborhood_zip_codes_id'), table_name='neighborhood_zip_codes')
    op.drop_index(op.f('ix_neighborhood_zip_codes_neighborhood'), table_name='neighborhood_zip_codes')
    op.create_index(op.f('ix_neighborhood_zip_codes_neighborhood'), 'neighborhood_zip_codes', ['neighborhood'], unique=False)
    op.create_unique_constraint(op.f('uq_neighborhood_zip_codes_neighborhood'), 'neighborhood_zip_codes', ['neighborhood'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_menu_item_attribute_values_menu_item_id'), table_name='menu_item_attribute_values')
    op.drop_index(op.f('ix_menu_item_attribute_values_id'), table_name='menu_item_attribute_values')
    op.drop_index(op.f('ix_menu_item_attribute_values_attribute_id'), table_name='menu_item_attribute_values')
    op.create_index(op.f('idx_menu_item_attr_values_item'), 'menu_item_attribute_values', ['menu_item_id'], unique=False)
    op.create_index(op.f('idx_menu_item_attr_values_attr'), 'menu_item_attribute_values', ['attribute_id'], unique=False)
    op.drop_index(op.f('ix_menu_item_attribute_selections_menu_item_id'), table_name='menu_item_attribute_selections')
    op.drop_index(op.f('ix_menu_item_attribute_selections_id'), table_name='menu_item_attribute_selections')
    op.create_index(op.f('idx_menu_item_attr_sel_item'), 'menu_item_attribute_selections', ['menu_item_id'], unique=False)
    op.drop_index(op.f('ix_item_type_attributes_item_type_id'), table_name='item_type_attributes')
    op.drop_index(op.f('ix_item_type_attributes_id'), table_name='item_type_attributes')
    op.create_index(op.f('idx_item_type_attributes_type'), 'item_type_attributes', ['item_type_id'], unique=False)
    op.create_table('by_pound_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('by_pound_categories_pkey')),
    sa.UniqueConstraint('slug', name=op.f('by_pound_categories_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_by_pound_categories_slug'), 'by_pound_categories', ['slug'], unique=False)
    # ### end Alembic commands ###
