"""add_store_tax_rates

Revision ID: cf65216705b5
Revises: m6f7g8h9i0j1
Create Date: 2025-12-20 23:40:52.530392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf65216705b5'
down_revision: Union[str, Sequence[str], None] = 'm6f7g8h9i0j1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_menu_items_category'), 'menu_items', ['category'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index('ix_orders_status_created_at', 'orders', ['status', 'created_at'], unique=False)
    op.add_column('stores', sa.Column('city_tax_rate', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('stores', sa.Column('state_tax_rate', sa.Float(), nullable=False, server_default='0.0'))
    op.drop_constraint(op.f('stores_store_id_key'), 'stores', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('stores_store_id_key'), 'stores', ['store_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('stores', 'state_tax_rate')
    op.drop_column('stores', 'city_tax_rate')
    op.drop_index('ix_orders_status_created_at', table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_menu_items_category'), table_name='menu_items')
    # ### end Alembic commands ###
