"""Add company table

Revision ID: d19f94b7638e
Revises: e045ece2f499
Create Date: 2025-12-14 21:28:42.663789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19f94b7638e'
down_revision: Union[str, Sequence[str], None] = 'e045ece2f499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bot_persona_name', sa.String(), nullable=False),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('headquarters_address', sa.String(), nullable=True),
    sa.Column('corporate_phone', sa.String(), nullable=True),
    sa.Column('corporate_email', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('business_hours', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.drop_index(op.f('ix_stores_store_id'), table_name='stores')
    op.create_index(op.f('ix_stores_store_id'), 'stores', ['store_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_store_id'), table_name='stores')
    op.create_index(op.f('ix_stores_store_id'), 'stores', ['store_id'], unique=False)
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
